function opt = mpoption_info_tspopf(selector)
%MPOPTION_INFO_CPLEX  Returns MATPOWER option info for TSPOPF.
%
%   DEFAULT_OPTS = MPOPTION_INFO_TSPOPF('D')
%   VALID_OPTS   = MPOPTION_INFO_TSPOPF('V')
%   EXCEPTIONS   = MPOPTION_INFO_TSPOPF('E')
%
%   Returns a structure for TSPOPF options for MATPOWER containing ...
%   (1) default options,
%   (2) valid options, or
%   (3) NESTED_STRUCT_COPY exceptions for setting options
%   ... depending on the value of the input argument.
%
%   This function is used by MPOPTION to set default options, check validity
%   of option names or modify option setting/copying behavior for this
%   subset of optional MATPOWER options.
%
%   See also MPOPTION.

%   TSPOPF for MATPOWER
%   $Id: mpoption_info_tspopf.m 2279 2014-01-17 18:43:59Z ray $
%   by Ray Zimmerman, PSERC Cornell
%   Copyright (c) 2014 by Power System Engineering Research Center (PSERC)
%   See http://www.pserc.cornell.edu/matpower/ for more info.

if nargin < 1
    selector = 'D';
end
if have_fcn('pdipmopf')
    switch upper(selector)
        case {'D', 'V'}     %% default and valid options
            opt = struct(...
                'pdipm',                struct(...
                    'step_control',         0, ...
                    'feastol',              0, ...
                    'gradtol',              1e-6, ...
                    'comptol',              1e-6, ...
                    'costtol',              1e-6, ...
                    'max_it',               150, ...
                    'sc',                   struct(...
                        'red_it',               20, ...
                        'smooth_ratio',         0.04    )), ...
                'tralm',                struct(...
                    'feastol',              0, ...
                    'primaltol',            5e-4, ...
                    'dualtol',              5e-4, ...
                    'costtol',              1e-5, ...
                    'major_it',             40, ...
                    'minor_it',             100, ...
                    'smooth_ratio',         0.04 ...
                ) ...
            );
        case 'E'            %% exceptions used by nested_struct_copy() for applying
            opt = struct([]);   %% no exceptions
        otherwise
            error('mpoption_info_tspopf: ''%s'' is not a valid input argument', selector);
    end
else
    opt = struct([]);       %% TSPOPF is not available
end
